# Generated by Django 2.2.11 on 2020-04-15 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(null=True)),
                ('duracao', models.IntegerField()),
                ('limite_participantes', models.IntegerField()),
                ('tipo_atividade', models.CharField(choices=[('VI', 'Visitas Instalações'), ('VL', 'Visitas Laboratórios'), ('AE', 'Atividades Experimentais'), ('AT', 'Atividades Tecnológicas'), ('FC', 'Feira das Ciências'), ('PL', 'Palestras'), ('CF', 'Conferências'), ('SM', 'Seminários'), ('TT', 'Tertúlias'), ('OE', 'Outras Atividades (Ensino)'), ('OC', 'Outras Atividades (Culturais)'), ('OD', 'Outras Atividades (Desportivas)'), ('EX', 'Exposições'), ('PS', 'Passeios'), ('OU', 'Outras Atividades')], max_length=2)),
                ('data', models.DateField(default=datetime.date.today)),
                ('validada', models.CharField(choices=[('RJ', 'Rejeitada'), ('PD', 'Pendente'), ('VD', 'Validada')], default='PD', max_length=2)),
                ('tipo_local', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('morada', models.TextField(null=True)),
                ('contacto', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Campus')),
            ],
            options={
                'unique_together': {('nome', 'campus')},
            },
        ),
        migrations.CreateModel(
            name='Faculdade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicoAlvo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('RJ', 'Rejeitada'), ('PA', 'Por Atribuir'), ('AT', 'Atribuida')], default='PA', max_length=2)),
                ('tipo_tarefa', models.CharField(choices=[('AV', 'Atividade'), ('PE', 'Percurso'), ('OT', 'Outra')], default='ATV', max_length=2)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('localizacao_grupo', models.CharField(max_length=255, null=True)),
                ('destino', models.CharField(max_length=255, null=True)),
                ('horario', models.TimeField(null=True)),
                ('dia', models.DateField(default=datetime.date.today)),
                ('cordenador', models.IntegerField(default=2)),
                ('coolaborador', models.IntegerField(default=3)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_atividade', to='diaabertoapp.Atividade')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacao', models.CharField(max_length=40)),
                ('edificio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Edificio')),
            ],
            options={
                'unique_together': {('identificacao', 'edificio')},
            },
        ),
        migrations.CreateModel(
            name='MaterialQuantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('atividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_quantidade', to='diaabertoapp.Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('faculdade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Faculdade')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Campus'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Departamento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Edificio'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='faculdade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Faculdade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='publico_alvo',
            field=models.ManyToManyField(related_name='publico_alvo', to='diaabertoapp.PublicoAlvo'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Sala'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tematicas',
            field=models.ManyToManyField(related_name='temas', to='diaabertoapp.Tematica'),
        ),
        migrations.CreateModel(
            name='SessaoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(null=True)),
                ('numero_colaboradores', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('atividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessao_atividade', to='diaabertoapp.Atividade')),
                ('sessao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diaabertoapp.Sessao')),
            ],
            options={
                'unique_together': {('atividade', 'sessao', 'dia')},
            },
        ),
    ]
