# Generated by Django 2.2.11 on 2020-06-19 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(null=True)),
                ('duracao', models.IntegerField()),
                ('limite_participantes', models.IntegerField()),
                ('data', models.DateField(default=datetime.date.today)),
                ('validada', models.CharField(choices=[('RJ', 'Rejeitada'), ('PD', 'Pendente'), ('VD', 'Validada')], default='PD', max_length=2)),
                ('tipo_local', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Atividade',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('morada', models.TextField(null=True)),
                ('contacto', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(null=True)),
            ],
            options={
                'db_table': 'Dia',
            },
        ),
        migrations.CreateModel(
            name='DiaAberto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('data_inicio', models.DateField(null=True)),
                ('data_fim', models.DateField(null=True)),
            ],
            options={
                'db_table': 'DiaAberto',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('mapa', models.CharField(default='diaabertoapp/maps/default.png', max_length=255)),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Campus')),
            ],
            options={
                'db_table': 'Edificio',
                'unique_together': {('nome', 'campus')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Material',
            },
        ),
        migrations.CreateModel(
            name='PublicoAlvo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'PublicoAlvo',
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField(null=True, unique=True)),
            ],
            options={
                'db_table': 'Sessao',
            },
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Tematica',
            },
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'TipoAtividade',
            },
        ),
        migrations.CreateModel(
            name='UnidadeOrganica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'UnidadeOrganica',
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nascimento', models.DateField(null=True)),
                ('numero_telemovel', models.CharField(blank=True, max_length=255, null=True)),
                ('cartao_cidadao', models.CharField(max_length=255, null=True)),
                ('deficiencias', models.CharField(blank=True, max_length=255, null=True)),
                ('permitir_localizacao', models.IntegerField(null=True)),
                ('utilizar_dados_pessoais', models.IntegerField(null=True)),
                ('validado', models.IntegerField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Departamento')),
                ('unidadeorganica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.UnidadeOrganica')),
            ],
            options={
                'db_table': 'Utilizador',
            },
        ),
        migrations.CreateModel(
            name='UtilizadorTipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'UtilizadorTipo',
            },
        ),
        migrations.CreateModel(
            name='UtilizadorParticipante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('escola', models.CharField(max_length=255)),
                ('area_estudos', models.CharField(max_length=255)),
                ('ano_estudos', models.IntegerField(blank=True, null=True)),
                ('checkin', models.IntegerField(blank=True, null=True)),
                ('inscricao_id', models.IntegerField()),
                ('utilizador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Utilizador')),
            ],
            options={
                'db_table': 'UtilizadorParticipante',
            },
        ),
        migrations.AddField(
            model_name='utilizador',
            name='utilizadortipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.UtilizadorTipo'),
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('RJ', 'Rejeitada'), ('PA', 'Por Atribuir'), ('AT', 'Atribuida')], default='PA', max_length=2)),
                ('tipo_tarefa', models.CharField(choices=[('AV', 'Atividade'), ('PE', 'Percurso'), ('OT', 'Outra')], default='ATV', max_length=2)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('localizacao_grupo', models.CharField(max_length=255, null=True)),
                ('destino', models.CharField(max_length=255, null=True)),
                ('horario', models.TimeField(null=True)),
                ('dia', models.DateField(default=datetime.date.today)),
                ('cordenador', models.IntegerField(default=2)),
                ('coolaborador', models.IntegerField(default=3)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_atividade', to='diaabertoapp.Atividade')),
            ],
            options={
                'db_table': 'Tarefa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacao', models.CharField(max_length=40)),
                ('mapa', models.CharField(default='diaabertoapp/maps/default.png', max_length=255)),
                ('edificio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Edificio')),
            ],
            options={
                'db_table': 'Sala',
                'unique_together': {('identificacao', 'edificio')},
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(blank=True, max_length=255, null=True)),
                ('conteudo', models.CharField(blank=True, max_length=255, null=True)),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('prioridade', models.IntegerField(blank=True, null=True)),
                ('visto', models.BooleanField(default=False)),
                ('utilizador_envia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilizador_envia', to='diaabertoapp.Utilizador')),
                ('utilizador_recebe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilizador_recebe', to='diaabertoapp.Utilizador')),
            ],
            options={
                'db_table': 'Notificacao',
            },
        ),
        migrations.CreateModel(
            name='MaterialQuantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('atividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_quantidade', to='diaabertoapp.Atividade')),
            ],
            options={
                'db_table': 'MaterialQuantidade',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='unidadeorganica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.UnidadeOrganica'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Campus'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Departamento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Edificio'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='publico_alvo',
            field=models.ManyToManyField(related_name='publico_alvo', to='diaabertoapp.PublicoAlvo'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Utilizador'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Sala'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tematicas',
            field=models.ManyToManyField(related_name='temas', to='diaabertoapp.Tematica'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.TipoAtividade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='unidadeorganica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.UnidadeOrganica'),
        ),
        migrations.CreateModel(
            name='SessaoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(null=True)),
                ('numero_colaboradores', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('atividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessao_atividade', to='diaabertoapp.Atividade')),
                ('sessao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Sessao')),
            ],
            options={
                'db_table': 'SessaoAtividade',
                'unique_together': {('atividade', 'sessao', 'dia')},
            },
        ),
    ]
