# Generated by Django 2.2.11 on 2020-06-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessaoatividade',
            old_name='dia',
            new_name='dias',
        ),
        migrations.AlterUniqueTogether(
            name='sessaoatividade',
            unique_together={('atividade', 'sessao', 'dias')},
        ),
    ]
