# Generated by Django 2.2.11 on 2020-06-25 03:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(null=True)),
                ('duracao', models.IntegerField()),
                ('limite_participantes', models.IntegerField()),
                ('data', models.DateField(default=datetime.date.today)),
                ('validada', models.CharField(choices=[('RJ', 'Rejeitada'), ('PD', 'Pendente'), ('VD', 'Validada')], default='PD', max_length=2)),
                ('tipo_local', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Atividade',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('morada', models.TextField(null=True)),
                ('contacto', models.CharField(max_length=40)),
                ('mapa_imagem', models.ImageField(default='diaabertoapp/maps/default.png', upload_to='diaabertoapp/maps/')),
            ],
            options={
                'db_table': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='Colaboracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_colaboracao', models.DateField(blank=True, null=True)),
                ('hora_inicio_colab', models.TimeField(blank=True, null=True)),
                ('hora_fim_colab', models.TimeField(blank=True, null=True)),
                ('percurso', models.IntegerField(blank=True, null=True)),
                ('sala_de_aula', models.IntegerField(blank=True, null=True)),
                ('tarefa_atribuida', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'colaboracao',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(null=True)),
            ],
            options={
                'db_table': 'Dia',
            },
        ),
        migrations.CreateModel(
            name='DiaAberto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('contacto', models.IntegerField(null=True)),
                ('data_inicio', models.DateField(null=True)),
                ('data_fim', models.DateField(null=True)),
                ('limite_inscricao_atividades', models.IntegerField()),
                ('limite_inscricao_participantes', models.IntegerField()),
            ],
            options={
                'db_table': 'DiaAberto',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('mapa_imagem', models.ImageField(default='diaabertoapp/maps/default.png', upload_to='diaabertoapp/maps/')),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Campus')),
            ],
            options={
                'db_table': 'Edificio',
                'unique_together': {('nome', 'campus')},
            },
        ),
        migrations.CreateModel(
            name='Ementa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('preco_aluno_economico', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco_aluno_normal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco_outro_economico', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco_outro', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'ementa',
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('morada', models.TextField(blank=True, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.IntegerField(blank=True, null=True)),
                ('localidade', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'escola',
            },
        ),
        migrations.CreateModel(
            name='Faculdade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Faculdade',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_chegada', models.TimeField()),
                ('hora_partida', models.TimeField()),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=datetime.date.today)),
                ('hora_check_in', models.TimeField()),
                ('check_in', models.IntegerField(default=0)),
                ('area_estudos', models.CharField(max_length=45)),
                ('ano_estudos', models.IntegerField()),
                ('escola', models.ForeignKey(blank=True, db_column='escola_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Escola')),
            ],
            options={
                'db_table': 'inscricao',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Material',
            },
        ),
        migrations.CreateModel(
            name='Percurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'percurso',
            },
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('sopa', models.CharField(blank=True, max_length=255)),
                ('sobremesa', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'prato',
            },
        ),
        migrations.CreateModel(
            name='PublicoAlvo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'PublicoAlvo',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacao', models.CharField(max_length=40)),
                ('mapa_imagem', models.ImageField(default='diaabertoapp/maps/default.png', upload_to='diaabertoapp/maps/')),
                ('edificio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Edificio')),
            ],
            options={
                'db_table': 'Sala',
                'unique_together': {('identificacao', 'edificio')},
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField(null=True, unique=True)),
            ],
            options={
                'db_table': 'Sessao',
            },
        ),
        migrations.CreateModel(
            name='SessaoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(null=True)),
                ('numero_colaboradores', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('n_alunos', models.PositiveIntegerField(default=0)),
                ('atividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessao_atividade', to='diaabertoapp.Atividade')),
                ('sessao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diaabertoapp.Sessao')),
            ],
            options={
                'db_table': 'SessaoAtividade',
                'unique_together': {('atividade', 'sessao', 'dia')},
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('RJ', 'Rejeitada'), ('PA', 'Por Atribuir'), ('AT', 'Atribuida')], default='PA', max_length=2)),
                ('tipo_tarefa', models.CharField(choices=[('AV', 'Atividade'), ('PE', 'Percurso'), ('OT', 'Outra')], default='AV', max_length=2)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('duracao', models.IntegerField(null=True)),
                ('horario', models.TimeField(null=True)),
                ('dia', models.DateField(default=datetime.date.today)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_atividade', to='diaabertoapp.Atividade')),
                ('colaboracao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Colaboracao')),
            ],
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Tematica',
            },
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'TipoAtividade',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transporte', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('capacidade', models.IntegerField()),
            ],
            options={
                'db_table': 'transporte',
            },
        ),
        migrations.CreateModel(
            name='Transporteproprio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('tipo_transporte', models.CharField(max_length=255)),
                ('transporte_para_campus', models.CharField(max_length=255, null=True)),
                ('transporte_entre_campus', models.CharField(max_length=255, null=True)),
                ('hora_chegada', models.TimeField()),
                ('hora_partida', models.TimeField()),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Inscricao')),
            ],
            options={
                'db_table': 'transporteproprio',
            },
        ),
        migrations.CreateModel(
            name='UnidadeOrganica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('campus', models.ForeignKey(db_column='campus', on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Campus')),
            ],
            options={
                'db_table': 'UnidadeOrganica',
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('numero_telemovel', models.IntegerField()),
                ('cartao_cidadao', models.IntegerField()),
                ('deficiencias', models.CharField(max_length=255)),
                ('permitir_localizacao', models.IntegerField()),
                ('utilizar_dados_pessoais', models.IntegerField()),
                ('validado', models.IntegerField(blank=True, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Departamento')),
                ('unidadeorganica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.UnidadeOrganica')),
            ],
            options={
                'db_table': 'Utilizador',
            },
        ),
        migrations.CreateModel(
            name='UtilizadorTipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'utilizadortipo',
            },
        ),
        migrations.CreateModel(
            name='UtilizadorTarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('colaboracao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Colaboracao')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='1+', to='diaabertoapp.Utilizador')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='1+', to='diaabertoapp.Utilizador')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Tarefa')),
            ],
            options={
                'db_table': 'utilizador_tarefa',
            },
        ),
        migrations.CreateModel(
            name='UtilizadorParticipante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('escola', models.CharField(max_length=255)),
                ('area_estudos', models.CharField(max_length=255)),
                ('ano_estudos', models.IntegerField(blank=True, null=True)),
                ('checkin', models.IntegerField(blank=True, null=True)),
                ('inscricao_id', models.IntegerField()),
                ('utilizador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Utilizador')),
            ],
            options={
                'db_table': 'UtilizadorParticipante',
            },
        ),
        migrations.AddField(
            model_name='utilizador',
            name='utilizadortipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.UtilizadorTipo'),
        ),
        migrations.CreateModel(
            name='UnidadeorganicaDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Departamento')),
                ('unidade_organica', models.ForeignKey(db_column='unidade_organica', on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.UnidadeOrganica')),
            ],
            options={
                'db_table': 'unidadeorganica_departamento',
            },
        ),
        migrations.CreateModel(
            name='TransporteUniversitarioHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Horario')),
                ('percurso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Percurso')),
                ('transporte_universitario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Transporte')),
            ],
            options={
                'db_table': 'transporte_universitario-horario',
            },
        ),
        migrations.CreateModel(
            name='TransporteproprioPercursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('hora', models.TimeField()),
                ('transporteproprio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Transporteproprio')),
            ],
            options={
                'db_table': 'transporteproprio_percursos',
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='coolaborador',
            field=models.ManyToManyField(related_name='tarefa_coolaborador', to='diaabertoapp.Utilizador'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='cordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestor_tarefa', to='diaabertoapp.Utilizador'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_destino', to='diaabertoapp.Sala'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='grupo',
            field=models.ManyToManyField(related_name='percurso_grupoM', to='diaabertoapp.Inscricao'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='localizacao_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_localizacao_grupo', to='diaabertoapp.Sala'),
        ),
        migrations.CreateModel(
            name='SessaoAtividadeInscricao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_alunos', models.IntegerField()),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='diaabertoapp.Inscricao')),
                ('sessaoAtividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='diaabertoapp.SessaoAtividade')),
            ],
            options={
                'db_table': 'SessaoAtividadeInscricao',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('hora', models.DateTimeField()),
                ('prioridade', models.IntegerField(blank=True, null=True)),
                ('assunto', models.TextField(blank=True, null=True)),
                ('notificacao_grupo', models.IntegerField(db_column='Notificacao_grupo', null=True)),
                ('utilizador_env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='1+', to='diaabertoapp.Utilizador')),
                ('utilizador_rec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='1+', to='diaabertoapp.Utilizador')),
            ],
            options={
                'db_table': 'Notificacao',
            },
        ),
        migrations.CreateModel(
            name='MaterialQuantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('atividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_quantidade', to='diaabertoapp.Atividade')),
            ],
            options={
                'db_table': 'MaterialQuantidade',
            },
        ),
        migrations.CreateModel(
            name='InscricaoIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizacao', models.IntegerField(blank=True, null=True)),
                ('ficheiro_autorizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('acompanhantes', models.IntegerField()),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Inscricao')),
            ],
            options={
                'db_table': 'inscricao_individual',
            },
        ),
        migrations.CreateModel(
            name='InscricaoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_participantes', models.IntegerField()),
                ('total_professores', models.IntegerField()),
                ('turma', models.CharField(max_length=255)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Inscricao')),
            ],
            options={
                'db_table': 'inscricao_grupo',
            },
        ),
        migrations.AddField(
            model_name='inscricao',
            name='unidadeorganica_checkin',
            field=models.ForeignKey(blank=True, db_column='unidadeorganica_checkin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.UnidadeOrganica'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='utilizador',
            field=models.ForeignKey(db_column='utilizador', on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Utilizador'),
        ),
        migrations.CreateModel(
            name='EmentaInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aluno_normal', models.IntegerField(blank=True, null=True)),
                ('numero_outro_normal', models.IntegerField(blank=True, null=True)),
                ('ementa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Ementa')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Inscricao')),
            ],
            options={
                'db_table': 'ementa_inscricao',
            },
        ),
        migrations.AddField(
            model_name='ementa',
            name='prato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Prato'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='faculdade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Faculdade'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='unidadeorganica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.UnidadeOrganica'),
        ),
        migrations.AddField(
            model_name='colaboracao',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Utilizador'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Campus'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Departamento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Edificio'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='publico_alvo',
            field=models.ManyToManyField(related_name='publico_alvo', to='diaabertoapp.PublicoAlvo'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Utilizador'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Sala'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tematicas',
            field=models.ManyToManyField(related_name='temas', to='diaabertoapp.Tematica'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.TipoAtividade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='unidadeorganica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.UnidadeOrganica'),
        ),
    ]
