# Generated by Django 2.2.11 on 2020-06-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transporte', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('capacidade', models.IntegerField()),
            ],
            options={
                'db_table': 'transporte',
            },
        ),
    ]
