# Generated by Django 2.2.11 on 2020-03-17 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localatividade',
            name='andar',
        ),
        migrations.RemoveField(
            model_name='localatividade',
            name='edificio',
        ),
        migrations.RemoveField(
            model_name='localatividade',
            name='sala',
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('andar', models.CharField(max_length=30, null=True)),
                ('sala', models.CharField(max_length=30, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('edificio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Edificio')),
            ],
        ),
        migrations.AddField(
            model_name='localatividade',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Local'),
        ),
    ]
