# Generated by Django 2.2.11 on 2020-04-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='validada',
            new_name='estado',
        ),
    ]
