# Generated by Django 2.2.11 on 2020-04-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
