# Generated by Django 2.2.11 on 2020-03-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('localizacao_grupo', models.CharField(max_length=255, null=True)),
                ('destino', models.CharField(max_length=255, null=True)),
                ('horario', models.TimeField(null=True, unique=True)),
                ('coordenador', models.IntegerField(default=2)),
                ('colaborador', models.IntegerField(default=3)),
            ],
        ),
    ]
