# Generated by Django 2.2.11 on 2020-03-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
