# Generated by Django 2.2.11 on 2020-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='mapa',
            field=models.CharField(default='maps/default.png', max_length=255),
        ),
    ]
