# Generated by Django 2.2.11 on 2020-06-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0002_transporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'percurso',
            },
        ),
    ]
