# Generated by Django 2.2.11 on 2020-06-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0002_sala_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='mapa',
            field=models.CharField(default='diaabertoapp/maps/default.png', max_length=255),
        ),
    ]
