# Generated by Django 2.2.11 on 2020-06-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0002_auto_20200625_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
