# Generated by Django 2.2.11 on 2020-04-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0002_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialquantidade',
            name='atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_quantidade', to='diaabertoapp.Atividade'),
        ),
        migrations.AlterField(
            model_name='sessaoatividade',
            name='atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessao_atividade', to='diaabertoapp.Atividade'),
        ),
    ]
