# Generated by Django 2.2.11 on 2020-03-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0002_auto_20200309_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('morada', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='LocalAtividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('andar', models.CharField(max_length=30)),
                ('sala', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=40)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Campus')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Edificio')),
            ],
        ),
    ]
