# Generated by Django 2.2.11 on 2020-04-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0002_auto_20200401_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='estado',
            field=models.CharField(choices=[('RJ', 'Rejeitada'), ('PA', 'Por Atribuir'), ('AT', 'Atribuida')], default='PA', max_length=2),
        ),
    ]
