# Generated by Django 2.2.11 on 2020-06-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0003_auto_20200619_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoatividade',
            name='dia',
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sessaoatividade',
            unique_together={('atividade', 'sessao', 'dia')},
        ),
    ]
