# Generated by Django 2.2.11 on 2020-06-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0003_auto_20200603_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='mapa',
            field=models.CharField(default='diaabertoapp/maps/default.png', max_length=255),
        ),
    ]
