# Generated by Django 2.2.11 on 2020-04-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0003_auto_20200401_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='horario_fim',
            field=models.TimeField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='horario_inicio',
            field=models.TimeField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tipo_tarefa',
            field=models.CharField(choices=[('AV', 'Atividade'), ('PE', 'Percurso'), ('OT', 'Outra')], default='ATV', max_length=2),
        ),
    ]
