# Generated by Django 2.2.11 on 2020-06-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0003_percurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_chegada', models.TimeField()),
                ('hora_partida', models.TimeField()),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'horario',
            },
        ),
    ]
