# Generated by Django 2.2.11 on 2020-04-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0003_utilizador'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculdade',
            table='Faculdade',
        ),
    ]
