# Generated by Django 2.2.11 on 2020-04-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0004_auto_20200425_1731'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campus',
            table='Campus',
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='Departamento',
        ),
    ]
