# Generated by Django 2.2.11 on 2020-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0004_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('sopa', models.CharField(blank=True, max_length=255)),
                ('sobremesa', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'prato',
            },
        ),
    ]
