# Generated by Django 2.2.11 on 2020-03-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0004_auto_20200317_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='tipo_local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.LocalAtividade'),
        ),
    ]
