# Generated by Django 2.2.11 on 2020-06-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0004_edificio_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoatividade',
            name='dia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Dia'),
        ),
    ]
