# Generated by Django 2.2.11 on 2020-04-01 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0004_auto_20200401_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_atividade', to='diaabertoapp.Atividade'),
        ),
    ]
