# Generated by Django 2.2.11 on 2020-06-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0004_auto_20200619_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='mapa_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='diaabertoapp/maps/'),
        ),
    ]
