# Generated by Django 2.2.11 on 2020-06-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0005_sala_mapa_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='mapa_imagem',
            field=models.ImageField(default='media/diaabertoapp/maps/default.png', upload_to='diaabertoapp/maps/'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='mapa_imagem',
            field=models.ImageField(default='media/diaabertoapp/maps/default.png', upload_to='diaabertoapp/maps/'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='mapa',
            field=models.CharField(default='media/default.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='sala',
            name='mapa',
            field=models.CharField(blank=True, default='media/diaabertoapp/maps/default.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='sala',
            name='mapa_imagem',
            field=models.ImageField(default='media/diaabertoapp/maps/default.png', upload_to='diaabertoapp/maps/'),
        ),
    ]
