# Generated by Django 2.2.11 on 2020-04-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0005_auto_20200401_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='horario_fim',
            new_name='horario',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='horario_inicio',
        ),
    ]
