# Generated by Django 2.2.11 on 2020-06-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0005_prato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ementa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('preco_aluno_economico', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco_aluno_normal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco_outro_economico', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco_outro', models.DecimalField(decimal_places=2, max_digits=4)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Prato')),
            ],
            options={
                'db_table': 'ementa',
            },
        ),
    ]
