# Generated by Django 2.2.11 on 2020-03-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0005_remove_localatividade_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localatividade',
            name='andar',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='localatividade',
            name='edificio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Edificio'),
        ),
        migrations.AlterField(
            model_name='localatividade',
            name='sala',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
