# Generated by Django 2.2.11 on 2020-03-19 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0005_auto_20200317_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='local',
        ),
        migrations.AddField(
            model_name='atividade',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Campus'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Edificio'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='sala',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
