# Generated by Django 2.2.11 on 2020-04-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0005_auto_20200425_1732'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atividade',
            table='Atividade',
        ),
        migrations.AlterModelTable(
            name='edificio',
            table='Edificio',
        ),
        migrations.AlterModelTable(
            name='material',
            table='Material',
        ),
        migrations.AlterModelTable(
            name='materialquantidade',
            table='MaterialQuantidade',
        ),
        migrations.AlterModelTable(
            name='publicoalvo',
            table='PublicoAlvo',
        ),
        migrations.AlterModelTable(
            name='sala',
            table='Sala',
        ),
        migrations.AlterModelTable(
            name='sessao',
            table='Sessao',
        ),
        migrations.AlterModelTable(
            name='sessaoatividade',
            table='SessaoAtividade',
        ),
        migrations.AlterModelTable(
            name='tarefa',
            table='Tarefa',
        ),
        migrations.AlterModelTable(
            name='tematica',
            table='Tematica',
        ),
        migrations.AlterModelTable(
            name='tipoatividade',
            table='TipoAtividade',
        ),
    ]
