# Generated by Django 2.2.11 on 2020-04-02 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0006_auto_20200402_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='dia',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='horario',
            field=models.TimeField(null=True),
        ),
    ]
