# Generated by Django 2.2.11 on 2020-06-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0006_ementa'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaaberto',
            name='contacto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='diaaberto',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diaaberto',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='TransporteUniversitarioHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Horario')),
                ('percurso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Percurso')),
                ('transporte_universitario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Transporte')),
            ],
            options={
                'db_table': 'transporte_universitario-horario',
            },
        ),
    ]
