# Generated by Django 2.2.11 on 2020-06-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0006_auto_20200620_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='mapa_imagem',
            field=models.ImageField(default='diaabertoapp/maps/default.png', upload_to='diaabertoapp/maps/'),
        ),
    ]
