# Generated by Django 2.2.11 on 2020-03-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0006_auto_20200309_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Campus'),
        ),
    ]
