# Generated by Django 2.2.11 on 2020-03-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0006_auto_20200319_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificio',
            name='campus',
        ),
    ]
