# Generated by Django 2.2.11 on 2020-03-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0007_edificio_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(null=True)),
                ('duracao', models.IntegerField()),
                ('limite_participantes', models.IntegerField()),
                ('validada', models.IntegerField()),
                ('tipo_atividade', models.CharField(max_length=255)),
                ('public_alvo', models.CharField(max_length=45)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.LocalAtividade')),
            ],
        ),
    ]
