# Generated by Django 2.2.11 on 2020-06-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0007_auto_20200624_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaaberto',
            name='titulo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
