# Generated by Django 2.2.11 on 2020-03-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0008_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localatividade',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
