# Generated by Django 2.2.11 on 2020-04-26 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0008_atividade_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.TipoAtividade'),
        ),
    ]
