# Generated by Django 2.2.11 on 2020-06-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0008_auto_20200624_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaaberto',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
