# Generated by Django 2.2.11 on 2020-03-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0009_auto_20200319_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Sala'),
        ),
    ]
