# Generated by Django 2.2.11 on 2020-06-22 17:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0009_auto_20200622_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('morada', models.TextField(blank=True, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.IntegerField(blank=True, null=True)),
                ('localidade', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'escola',
            },
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={},
        ),
        migrations.AddField(
            model_name='tarefa',
            name='duracao',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='coolaborador',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='coolaborador',
            field=models.ManyToManyField(related_name='tarefa_coolaborador', to='diaabertoapp.Utilizador'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='cordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestor_tarefa', to='diaabertoapp.Utilizador'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_destino', to='diaabertoapp.Sala'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='localizacao_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_localizacao_grupo', to='diaabertoapp.Sala'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tipo_tarefa',
            field=models.CharField(choices=[('AV', 'Atividade'), ('PE', 'Percurso'), ('OT', 'Outra')], default='AV', max_length=2),
        ),
        migrations.AlterModelTable(
            name='tarefa',
            table=None,
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=datetime.date.today)),
                ('hora_check_in', models.TimeField()),
                ('check_in', models.IntegerField(default=0)),
                ('area_estudos', models.CharField(max_length=45)),
                ('ano_estudos', models.IntegerField()),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Escola')),
                ('unidadeorganica_checkin', models.ForeignKey(blank=True, db_column='unidadeorganica_checkin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.UnidadeOrganica')),
                ('utilizador', models.ForeignKey(db_column='utilizador', on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Utilizador')),
            ],
            options={
                'db_table': 'inscricao',
            },
        ),
        migrations.CreateModel(
            name='Colaboracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_colaboracao', models.DateField()),
                ('hora_inicio_colab', models.TimeField()),
                ('hora_fim_colab', models.TimeField()),
                ('percurso', models.IntegerField(blank=True, null=True)),
                ('sala_de_aula', models.IntegerField(blank=True, null=True)),
                ('tarefa_atribuida', models.IntegerField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diaabertoapp.Utilizador')),
            ],
            options={
                'db_table': 'colaboracao',
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='grupo',
            field=models.ManyToManyField(related_name='percurso_grupoM', to='diaabertoapp.Inscricao'),
        ),
    ]
