# Generated by Django 2.2.11 on 2020-06-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0009_diaaberto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoAtividadeInscricao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_alunos', models.IntegerField()),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='diaabertoapp.Inscricao')),
                ('sessaoAtividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='diaabertoapp.SessaoAtividade')),
            ],
            options={
                'db_table': 'SessaoAtividadeInscricao',
            },
        ),
    ]
