# Generated by Django 2.2.11 on 2020-04-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0009_auto_20200426_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
