# Generated by Django 2.2.11 on 2020-03-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0009_auto_20200309_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
