# Generated by Django 2.2.11 on 2020-03-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0010_auto_20200319_1647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edificio',
            unique_together={('campus', 'nome')},
        ),
    ]
