# Generated by Django 2.2.11 on 2020-05-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0010_utilizador_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculdade',
            new_name='UnidadeOrganica',
        ),
        migrations.RenameField(
            model_name='atividade',
            old_name='faculdade',
            new_name='unidadeorganica',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='faculdade',
            new_name='unidadeorganica',
        ),
        migrations.RenameField(
            model_name='utilizador',
            old_name='faculdade',
            new_name='unidadeorganica',
        ),
        migrations.AlterModelTable(
            name='unidadeorganica',
            table='UnidadeOrganica',
        ),
    ]
