# Generated by Django 2.2.11 on 2020-06-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0010_sessaoatividadeinscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='colaboracao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Colaboracao'),
        ),
    ]
