# Generated by Django 2.2.11 on 2020-03-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0010_tematica'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='data_submissao',
            field=models.DateField(null=True),
        ),
    ]
