# Generated by Django 2.2.11 on 2020-03-09 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0011_atividade_data_submissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='data_submissao',
        ),
        migrations.AddField(
            model_name='atividade',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
