# Generated by Django 2.2.11 on 2020-06-25 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0011_tarefa_colaboracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='utilizador_envia',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='utilizador_recebe',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='visto',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='notificacao_grupo',
            field=models.IntegerField(db_column='Notificacao_grupo', null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='utilizador_env',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='utilizador_env', to='diaabertoapp.Utilizador'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='utilizador_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='utilizador_rec', to='diaabertoapp.Utilizador'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='assunto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='notificacao',
            table='notificacoes',
        ),
    ]
