# Generated by Django 2.2.11 on 2020-05-06 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0011_auto_20200505_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoatividade',
            name='sessao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Sessao'),
        ),
    ]
