# Generated by Django 2.2.11 on 2020-06-25 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0012_auto_20200625_0148'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notificacao',
            table='Notificacao',
        ),
    ]
