# Generated by Django 2.2.11 on 2020-05-06 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0012_auto_20200506_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Campus'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Departamento'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Edificio'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Sala'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='unidadeorganica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.UnidadeOrganica'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='unidadeorganica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.UnidadeOrganica'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Campus'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='edificio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diaabertoapp.Edificio'),
        ),
    ]
