# Generated by Django 2.2.11 on 2020-03-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0012_auto_20200319_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
