# Generated by Django 2.2.11 on 2020-03-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0012_auto_20200309_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='validada',
            field=models.CharField(choices=[('RJ', 'Rejeitada'), ('PD', 'Pendente'), ('VL', 'Validada')], default='PD', max_length=2),
        ),
    ]
