# Generated by Django 2.2.11 on 2020-03-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0013_auto_20200319_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculdade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sala',
            name='identificacao',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together={('identificacao', 'edificio')},
        ),
    ]
