# Generated by Django 2.2.11 on 2020-05-06 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0013_auto_20200506_2339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessaoatividade',
            unique_together=set(),
        ),
    ]
