# Generated by Django 2.2.11 on 2020-05-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0014_auto_20200506_2344'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessaoatividade',
            unique_together={('atividade', 'sessao', 'dia')},
        ),
    ]
