# Generated by Django 2.2.11 on 2020-03-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0014_auto_20200320_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='faculdade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Faculdade'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('faculdade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Faculdade')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Departamento'),
        ),
    ]
