# Generated by Django 2.2.11 on 2020-03-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0015_auto_20200320_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicoAlvo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='publico_alvo',
        ),
        migrations.AddField(
            model_name='atividade',
            name='publico_alvo',
            field=models.ManyToManyField(related_name='publico_alvo', to='diaabertoapp.PublicoAlvo'),
        ),
    ]
