# Generated by Django 2.2.11 on 2020-03-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0016_auto_20200309_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='validada',
            field=models.CharField(choices=[('Rejeitada', 'Rejeitada'), ('Pendente', 'Pendente'), ('Validada', 'Validada')], default='Pendente', max_length=32),
        ),
    ]
