# Generated by Django 2.2.11 on 2020-03-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0017_auto_20200309_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.CharField(choices=[('Visitas Instalações', 'Visitas Instalações'), ('Visitas Laboratórios', 'Visitas Laboratórios'), ('Atividades Experimentais', 'Atividades Experimentais'), ('Atividades Tencnológicas', 'Atividades Tencnológicas'), ('Feira das Ciências', 'Feira das Ciências'), ('Palestras', 'Palestras'), ('Conferências', 'Conferências'), ('Seminários', 'Seminários'), ('Tertúlias', 'Tertúlias'), ('Outras Atividades (Ensino)', 'Outras Atividades (Ensino)'), ('Outras Atividades (Culturais)', 'Outras Atividades (Culturais)'), ('Outras Atividades (Desportivas)', 'Outras Atividades (Desportivas)'), ('Exposições', 'Exposições'), ('Passeios', 'Passeios'), ('Outras Atividades', 'Outras Atividades')], max_length=32),
        ),
    ]
