# Generated by Django 2.2.11 on 2020-03-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0018_auto_20200331_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoatividade',
            name='numero_colaboradores',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='sessaoatividade',
            unique_together={('atividade', 'sessao', 'dia')},
        ),
    ]
