# Generated by Django 2.2.11 on 2020-03-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0019_auto_20200310_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='validada',
            field=models.CharField(choices=[('RJ', 'Rejeitada'), ('PD', 'Pendente'), ('VD', 'Validada')], default='PD', max_length=2),
        ),
    ]
