# Generated by Django 2.2.11 on 2020-03-11 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0021_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='materiais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diaabertoapp.Material'),
        ),
    ]
