# Generated by Django 2.2.11 on 2020-03-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0023_auto_20200311_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='atividades',
            field=models.ManyToManyField(to='diaabertoapp.Atividade'),
        ),
    ]
