# Generated by Django 2.2.11 on 2020-03-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0024_material_atividades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtividadeMaterial',
        ),
    ]
