# Generated by Django 2.2.11 on 2020-03-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0025_delete_atividadematerial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='atividades',
        ),
        migrations.AddField(
            model_name='atividade',
            name='materiais',
            field=models.ManyToManyField(to='diaabertoapp.Material'),
        ),
    ]
