# Generated by Django 2.2.11 on 2020-03-12 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0026_auto_20200311_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialQuantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('atividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_quantidade', to='diaabertoapp.Atividade')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_quantidade', to='diaabertoapp.Material')),
            ],
        ),
    ]
