# Generated by Django 2.2.11 on 2020-03-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0027_materialquantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='materiais',
        ),
    ]
