# Generated by Django 2.2.11 on 2020-03-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0028_remove_atividade_materiais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.CharField(choices=[('VI', 'Visitas Instalações'), ('VL', 'Visitas Laboratórios'), ('AE', 'Atividades Experimentais'), ('AT', 'Atividades Tecnológicas'), ('FC', 'Feira das Ciências'), ('PL', 'Palestras'), ('CF', 'Conferências'), ('SM', 'Seminários'), ('TT', 'Tertúlias'), ('OE', 'Outras Atividades (Ensino)'), ('OC', 'Outras Atividades (Culturais)'), ('OD', 'Outras Atividades (Desportivas)'), ('EX', 'Exposições'), ('PS', 'Passeios'), ('OU', 'Outras Atividades')], max_length=2),
        ),
    ]
