# Generated by Django 2.2.11 on 2020-03-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0030_auto_20200314_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='tematicas',
            field=models.ManyToManyField(to='diaabertoapp.Tematica'),
        ),
    ]
