# Generated by Django 2.2.11 on 2020-03-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaabertoapp', '0031_atividade_tematicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tematicas',
            field=models.ManyToManyField(related_name='temas', to='diaabertoapp.Tematica'),
        ),
    ]
